# sonar.projectKey=roboshop-catalogue
# sonar.projectName=roboshop-catalogue
# sonar.sources=.
# sonar.exclusions=node_modules,db,Jenkinsfile,Dockerfile

# Unique identifier for the project (must be unique in SonarQube)
sonar.projectKey=roboshop-catalogue

# Name of the project shown in SonarQube UI
sonar.projectName=roboshop-catalogue

# Path to source code ('.' means current directory)
sonar.sources=.

# Files/folders to exclude from scanning
# node_modules → external dependencies
# db → database scripts (optional to analyze)
# Jenkinsfile → CI/CD pipeline config file
# Dockerfile → container configuration file
sonar.exclusions=**/node_modules/**,**/db/**,Jenkinsfile,Dockerfile